version: 1

env:
  - GOOS=linux
  - GOARCH=amd64

builds:
  - id: dummy-server
    binary: binary
    main: ./cmd/main.go
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
